import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import dns from "node:dns"
import { ToastContainer } from "react-toastify";

dns.setServers(['8.8.8.8', '8.8.4.4'])

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Navbar></Navbar>
        <main className="max-w-[1140px] mx-auto">
          {children}
        </main>
        <ToastContainer />
        <Footer></Footer>
      </body>
    </html>
  );
}
